<a href="https://colab.research.google.com/github/pavstar619/ML-Classify-Male-Female/blob/master/male_female_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [87]:
#import enssential dependencies from sklearn
from sklearn import ensemble
from sklearn import svm
import pandas as pd 
import random
import numpy as np

#[height, weight, shoe size]
X = [[181,80,44], [177, 70, 43], [160, 60, 38], [154, 54,37], 
	 [166,65,40], [190,90,47], [175,64,39], [177,70,40], [159, 55,39], [171,75,42], [181,85,43], [220,115,53], [210,110,51], [230,120,55]]

#gender 1 is MALE, 0 is FEMALE
Y =  [1, 0, 0, 0, 1, 1,
	  1, 0,1, 0, 1, 2, 2, 2]

""" df = pd.read_excel('test.xlsx', 'sheet1')
X = df['Features'].values.tolist()
Y = df['Gender'].values.tolist()
print(X)
print(Y) """

#create variables with classifiers
randomForest = ensemble.RandomForestClassifier()
svm = svm.SVC(gamma='auto')
adaBoost = ensemble.AdaBoostClassifier()

#fit them
randomForest = randomForest.fit(X,Y)
svm = svm.fit(X,Y)
adaBoost = adaBoost.fit(X,Y)

''' #Take inputs
print('Write inputs cm, kg, size')
a, b, c = input().split()

#create prediction variables for results
predictionForRandomForest = randomForest.predict([[a,b,c]])
predictionForSVM = svm.predict([[a,b,c]])
predictionForAdaBoost = adaBoost.predict([[a,b,c]])


#print all the results
print("2 for GIANT, 1 for MALE and 0 for FEMALE")
print("RandomForest: ", predictionForRandomForest)
print("SVM: ", predictionForSVM)
print("AdaBoost: ", predictionForAdaBoost)
 '''
y_pred_randomForest = []
y_pred_svm = []
y_pred_adaBoost = []

for x in range(14): 
	a, b, c = random.randint(152,240), random.randint(40,90), random.randint(35,45)
	predictionForRandomForest = randomForest.predict([[a,b,c]])
	predictionForSVM = svm.predict([[a,b,c]])
	predictionForAdaBoost = adaBoost.predict([[a,b,c]])
	print(a,b,c)
 
	y_pred_randomForest.append(int(predictionForRandomForest))
	y_pred_svm.append(int(predictionForSVM))
	y_pred_adaBoost.append(int(predictionForAdaBoost))
print("RandomForest: ", y_pred_randomForest)
print("SVM: ", y_pred_svm)
print("AdaBoost: ", y_pred_adaBoost)


216 58 42
190 57 36
200 73 43
189 83 44
228 51 42
193 89 41
199 51 40
186 89 41
219 84 38
217 79 43
206 66 36
199 88 43
215 59 38
176 52 45
RandomForest:  [0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1]
SVM:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
AdaBoost:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
y_true = [1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 2, 2] #real values
y_pred = [0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 2, 1, 2, 1] #fake values
cm = confusion_matrix(y_true,y_pred, labels=[0,1,2])
print(cm)

[[2 2 1]
 [3 2 1]
 [0 2 1]]


In [ ]:
acc = accuracy_score(y_true, y_pred)
acc

0.35714285714285715

In [ ]:
prec = precision_score(y_true,y_pred, average = 'macro')
prec

0.35555555555555557

In [ ]:
f1 = f1_score(y_true,y_pred, average = 'macro')
f1

0.35555555555555557

In [ ]:
recall = recall_score(y_true,y_pred, average = 'macro')
recall


0.35555555555555557

In [12]:
import random
for x in range(14): 
  a, b, c = random.randint(152,240), random.randint(40,90), random.randint(35,45)
  print(a,b,c)

229 78 39
224 50 36
197 48 43
204 82 43
192 63 42
200 85 42
223 62 39
175 78 38
183 56 43
176 83 42
175 59 44
229 79 42
154 76 39
204 73 36
