<a href="https://colab.research.google.com/github/pavstar619/ML-Classify-Male-Female/blob/master/male_female_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
#import enssential dependencies from sklearn
from sklearn import ensemble
from sklearn import svm
import pandas as pd 
import random
import numpy as np

#[height, weight, shoe size]
X = [[181,80,44], [177, 70, 43], [160, 60, 38], [154, 54,37], 
	 [166,65,40], [190,90,47], [175,64,39], [177,70,40], [159, 55,39], [171,75,42], [181,85,43], [220,115,53], [210,110,51], [230,120,55]]

#gender 1 is MALE, 0 is FEMALE
Y =  [1, 0, 0, 0, 1, 1,
	  1, 0,1, 0, 1, 2, 2, 2]

""" df = pd.read_excel('test.xlsx', 'sheet1')
X = df['Features'].values.tolist()
Y = df['Gender'].values.tolist()
print(X)
print(Y) """

#create variables with classifiers
randomForest = ensemble.RandomForestClassifier()
svm = svm.SVC(gamma='auto')
adaBoost = ensemble.AdaBoostClassifier()

#fit them
randomForest = randomForest.fit(X,Y)
svm = svm.fit(X,Y)
adaBoost = adaBoost.fit(X,Y)

''' #Take inputs
print('Write inputs cm, kg, size')
a, b, c = input().split()

#create prediction variables for results
predictionForRandomForest = randomForest.predict([[a,b,c]])
predictionForSVM = svm.predict([[a,b,c]])
predictionForAdaBoost = adaBoost.predict([[a,b,c]])


#print all the results
print("2 for GIANT, 1 for MALE and 0 for FEMALE")
print("RandomForest: ", predictionForRandomForest)
print("SVM: ", predictionForSVM)
print("AdaBoost: ", predictionForAdaBoost)
 '''
y_pred_randomForest = []
y_pred_svm = []
y_pred_adaBoost = []
height = []
weight = []
shoesize = []

for x in range(14): 
	a, b, c = random.randint(152,240), random.randint(40,90), random.randint(35,45)
	predictionForRandomForest = randomForest.predict([[a,b,c]])
	predictionForSVM = svm.predict([[a,b,c]])
	predictionForAdaBoost = adaBoost.predict([[a,b,c]])
	print(a,b,c)
	''' height.append(a)
	weight.append(b)
	shoesize.append(c) '''
 
	y_pred_randomForest.append(int(predictionForRandomForest))
	y_pred_svm.append(int(predictionForSVM))
	y_pred_adaBoost.append(int(predictionForAdaBoost))
print("RandomForest: ", y_pred_randomForest)
print("SVM: ", y_pred_svm)
print("AdaBoost: ", y_pred_adaBoost)


180 71 45
220 79 38
181 78 36
198 75 39
190 89 38
182 45 38
200 55 36
166 68 37
171 66 36
177 78 45
239 53 36
158 43 40
199 69 38
176 81 44
RandomForest:  [1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1]
SVM:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
AdaBoost:  [1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1]
[180, 220, 181, 198, 190, 182, 200, 166, 171, 177, 239, 158, 199, 176]
[71, 79, 78, 75, 89, 45, 55, 68, 66, 78, 53, 43, 69, 81]
[45, 38, 36, 39, 38, 38, 36, 37, 36, 45, 36, 40, 38, 44]


In [2]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
''' y_true = [1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 2, 2] #real values
y_pred = [0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 2, 1, 2, 1] #fake values '''
cm_randomForest = confusion_matrix(Y,y_pred_randomForest, labels=[0,1,2])
cm_svm = confusion_matrix(Y,y_pred_svm, labels=[0,1,2])
cm_adaBoost = confusion_matrix(Y,y_pred_adaBoost, labels=[0,1,2])
print(cm_randomForest)
print(cm_svm)
print(cm_adaBoost)

[[3 2 0]
 [1 5 0]
 [0 3 0]]
[[0 5 0]
 [0 6 0]
 [0 3 0]]
[[2 3 0]
 [1 5 0]
 [1 2 0]]


In [3]:
acc_randomForest = accuracy_score(Y, y_pred_randomForest)
acc_svm = accuracy_score(Y, y_pred_svm)
acc_adaBoost = accuracy_score(Y, y_pred_adaBoost)
print(acc_randomForest)
print(acc_svm)
print(acc_adaBoost)

0.5714285714285714
0.42857142857142855
0.5


In [4]:
prec_randomForest = precision_score(Y,y_pred_randomForest, average = 'macro')
prec_svm = precision_score(Y,y_pred_svm, average = 'macro')
prec_adaBoost = precision_score(Y,y_pred_adaBoost, average = 'macro')
print(prec_randomForest)
print(prec_svm)
print(prec_adaBoost)

0.4166666666666667
0.14285714285714285
0.3333333333333333


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [5]:
f1_randomForest = f1_score(Y,y_pred_randomForest, average = 'macro')
f1_svm = f1_score(Y,y_pred_svm, average = 'macro')
f1_adaBoost = f1_score(Y,y_pred_adaBoost, average = 'macro')
print(f1_randomForest)
print(f1_svm)
print(f1_adaBoost)

0.4305555555555555
0.19999999999999998
0.35648148148148145


In [6]:
recall_randomForest = recall_score(Y,y_pred_randomForest, average = 'macro')
recall_svm = recall_score(Y,y_pred_svm, average = 'macro')
recall_adaBoost = recall_score(Y,y_pred_adaBoost, average = 'macro')
print(recall_randomForest)
print(recall_svm)
print(recall_adaBoost)


0.4777777777777778
0.3333333333333333
0.41111111111111115


In [25]:
# Make a dataset
''' data = {'Height' : height, 'Weight' : weight, 'Shoesize' : shoesize}
df = pd.DataFrame(data , columns= ['Height', 'Weight', 'Shoesize'])
df '''

Height  Weight  Shoesize
0      180      71        45
1      220      79        38
2      181      78        36
3      198      75        39
4      190      89        38
5      182      45        38
6      200      55        36
7      166      68        37
8      171      66        36
9      177      78        45
10     239      53        36
11     158      43        40
12     199      69        38
13     176      81        44

In [33]:
#FOR DOWNLOADING CSV
''' from google.colab import files
df.to_csv('malefemale.csv') 
files.download('malefemale.csv') '''

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>