<a href="https://colab.research.google.com/github/pavstar619/ML-Classify-Male-Female/blob/master/male_female_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
#import enssential dependencies from sklearn
from sklearn import ensemble
from sklearn import svm
import pandas as pd 
import random
import numpy as np

#[height, weight, shoe size]
X = [[181,80,44], [177, 70, 43], [160, 60, 38], [154, 54,37], 
	 [166,65,40], [190,90,47], [175,64,39], [177,70,40], [159, 55,39], [171,75,42], [181,85,43], [220,115,53], [210,110,51], [230,120,55]]

#gender 1 is MALE, 0 is FEMALE
Y =  [1, 0, 0, 0, 1, 1,
	  1, 0,1, 0, 1, 2, 2, 2]

""" df = pd.read_excel('test.xlsx', 'sheet1')
X = df['Features'].values.tolist()
Y = df['Gender'].values.tolist()
print(X)
print(Y) """

#create variables with classifiers
randomForest = ensemble.RandomForestClassifier()
svm = svm.SVC(gamma='auto')
adaBoost = ensemble.AdaBoostClassifier()

#fit them
randomForest = randomForest.fit(X,Y)
svm = svm.fit(X,Y)
adaBoost = adaBoost.fit(X,Y)

''' #Take inputs
print('Write inputs cm, kg, size')
a, b, c = input().split()

#create prediction variables for results
predictionForRandomForest = randomForest.predict([[a,b,c]])
predictionForSVM = svm.predict([[a,b,c]])
predictionForAdaBoost = adaBoost.predict([[a,b,c]])


#print all the results
print("2 for GIANT, 1 for MALE and 0 for FEMALE")
print("RandomForest: ", predictionForRandomForest)
print("SVM: ", predictionForSVM)
print("AdaBoost: ", predictionForAdaBoost)
 '''
y_pred_randomForest = []
y_pred_svm = []
y_pred_adaBoost = []
height = []
weight = []
shoesize = []

for x in range(14): 
	a, b, c = random.randint(152,240), random.randint(40,90), random.randint(35,45)
	predictionForRandomForest = randomForest.predict([[a,b,c]])
	predictionForSVM = svm.predict([[a,b,c]])
	predictionForAdaBoost = adaBoost.predict([[a,b,c]])
	print(a,b,c)
	''' height.append(a)
	weight.append(b)
	shoesize.append(c) '''
 
	y_pred_randomForest.append(int(predictionForRandomForest))
	y_pred_svm.append(int(predictionForSVM))
	y_pred_adaBoost.append(int(predictionForAdaBoost))
print("RandomForest: ", y_pred_randomForest)
print("SVM: ", y_pred_svm)
print("AdaBoost: ", y_pred_adaBoost)


167 65 45
232 54 35
187 58 42
213 68 39
188 50 39
190 46 40
170 85 41
198 83 43
226 87 35
172 80 43
168 74 42
200 81 39
152 40 35
199 80 36
RandomForest:  [1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1]
SVM:  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
AdaBoost:  [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1]


In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, f1_score, recall_score
''' y_true = [1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 2, 2, 2] #real values
y_pred = [0, 1, 0, 1, 0, 1, 0, 2, 1, 0, 2, 1, 2, 1] #fake values '''
cm_randomForest = confusion_matrix(Y,y_pred_randomForest, labels=[0,1,2])
cm_svm = confusion_matrix(Y,y_pred_svm, labels=[0,1,2])
cm_adaBoost = confusion_matrix(Y,y_pred_adaBoost, labels=[0,1,2])
print(cm_randomForest)
print(cm_svm)
print(cm_adaBoost)

[[2 3 0]
 [2 4 0]
 [1 2 0]]
[[0 5 0]
 [0 6 0]
 [0 3 0]]
[[0 5 0]
 [2 4 0]
 [1 2 0]]


In [32]:
acc_randomForest = accuracy_score(Y, y_pred_randomForest)
acc_svm = accuracy_score(Y, y_pred_svm)
acc_adaBoost = accuracy_score(Y, y_pred_adaBoost)
print(acc_randomForest)
print(acc_svm)
print(acc_adaBoost)

0.42857142857142855
0.42857142857142855
0.2857142857142857


In [33]:
prec_randomForest = precision_score(Y,y_pred_randomForest, average = 'macro')
prec_svm = precision_score(Y,y_pred_svm, average = 'macro')
prec_adaBoost = precision_score(Y,y_pred_adaBoost, average = 'macro')
print(prec_randomForest)
print(prec_svm)
print(prec_adaBoost)

0.2814814814814815
0.14285714285714285
0.12121212121212122


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [34]:
f1_randomForest = f1_score(Y,y_pred_randomForest, average = 'macro')
f1_svm = f1_score(Y,y_pred_svm, average = 'macro')
f1_adaBoost = f1_score(Y,y_pred_adaBoost, average = 'macro')
print(f1_randomForest)
print(f1_svm)
print(f1_adaBoost)

0.3111111111111111
0.19999999999999998
0.15686274509803924


In [35]:
recall_randomForest = recall_score(Y,y_pred_randomForest, average = 'macro')
recall_svm = recall_score(Y,y_pred_svm, average = 'macro')
recall_adaBoost = recall_score(Y,y_pred_adaBoost, average = 'macro')
print(recall_randomForest)
print(recall_svm)
print(recall_adaBoost)


0.35555555555555557
0.3333333333333333
0.2222222222222222


In [36]:
# Make a dataset
''' data = {'Height' : height, 'Weight' : weight, 'Shoesize' : shoesize}
df = pd.DataFrame(data , columns= ['Height', 'Weight', 'Shoesize'])
df '''

" data = {'Height' : height, 'Weight' : weight, 'Shoesize' : shoesize}\ndf = pd.DataFrame(data , columns= ['Height', 'Weight', 'Shoesize'])\ndf "

In [37]:
#FOR DOWNLOADING CSV
''' from google.colab import files
df.to_csv('malefemale.csv') 
files.download('malefemale.csv') '''

" from google.colab import files\ndf.to_csv('malefemale.csv') \nfiles.download('malefemale.csv') "

In [38]:
results_dict = {'Classifier' : ['RandomForest', 'SVM', 'AdaBoost'],
                'Accuracy':[acc_randomForest, acc_svm, acc_adaBoost],
                'Precision':[prec_randomForest, prec_svm, prec_adaBoost],
                'F1 Score':[f1_randomForest, f1_svm, f1_adaBoost]}
results = pd.DataFrame(results_dict)
print(results)

     Classifier  Accuracy  Precision  F1 Score
0  RandomForest  0.428571   0.281481  0.311111
1           SVM  0.428571   0.142857  0.200000
2      AdaBoost  0.285714   0.121212  0.156863
